// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "meta": string;
      "citekey": string;
      "tag_norecid": string;
      "tag_enable": boolean;
      "arXivInfo": string;
      "arXivURL": boolean;
      "newpublication": boolean;
      "tag_newpub": string;
    };
  }
}
