export const journalDict: { [key: string]: string } = {
  "Ann. Rev. Nucl. Part. Sci.": "Annual Review of Nuclear and Particle Science",
  "Commun. Math. Phys.": "Communications in Mathematical Physics",
  "Comput. Phys. Commun.": "Computer Physics Communications",
  "Eur. Phys. J. C": "The European Physical Journal C",
  "Front. in Phys.": "Frontiers in Physics",
  "Int. J. Mod. Phys. A": "International Journal of Modern Physics A",
  "J. Phys. A": "Journal of Physics A",
  "J. Phys. G": "Journal of Physics G",
  "JCAP": "Journal of Cosmology and Astrophysics",
  "JHEP": "Journal of High Energy Physics",
  "LHEP": "Letters in High Energy Physics",
  "Nature Rev. Phys.": "Nature Reviews Physics",
  "Nucl. Phys. B": "Nuclear Physics B",
  "Phys. Lett. B": "Physics Letters B",
  "Phys. Rept.": "Physics Reports",
  "Phys. Rev.": "Physical Review",
  "Phys. Rev. D": "Physical Review D",
  "Phys. Rev. Lett.": "Physical Review Letters",
  "PoS": "Proceedings of Science",
  "Rev. Mod. Phys.": "Reviews of Modern Physics",
  "SciPost Phys.": "SciPost Physics",
  "SciPost Phys. Proc.": "SciPost Physics Proceedings",
  "Universe": "Universe",
};
